---
 - name: remove nginx default
   sudo: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
 - name: setup nginx sites available
   sudo: yes
   command: ln -s /etc/nginx/sites-available/storage /etc/nginx/sites-enabled/storage creates=/etc/nginx/sites-enabled/storage
 
 - name: restart nginx
   sudo: yes
   service: name=nginx state=reloaded
   
 - name: restart archivematica-storage-service
   sudo: yes
   service: name=archivematica-storage-service state=restarted enabled=yes
   when: ansible_virtualization_type != "docker"
