---

 - name: restart dashboard
   sudo: yes
   service: name=archivematica-dashboard state=reloaded enabled=yes
 - name: run freshclam
   sudo: yes
   command: freshclam
 - name: restart clamav
   sudo: yes
   service: name=clamav-daemon state=started
 - name: restart elasticsearch
   sudo: yes
   service: name=elasticsearch state=restarted
 - name: restart gearman
   sudo: yes
   service: name=gearman-job-server state=reloaded
 - name: start mcp-server
   sudo: yes
   service: name=archivematica-mcp-server state=started
 - name: start mcp-client
   sudo: yes
   service: name=archivematica-mcp-client state=started
 - name: start fits
   sudo: yes
   service: name=fits state=started
