---
- name: Install python-curl
  apt: pkg='python-pycurl' state=present
  sudo: yes

- name: Add archivematica PPA
  sudo: yes
  apt_repository: repo=ppa:'{{ item }}' state=present
  with_items:
    - '{{ ppa }}'

- name: Install archivematica storage service packages
  sudo: yes
  apt: pkg='{{ item }}' state=present update_cache=yes
  with_items:
    - archivematica-storage-service
